### ISSUE TITLE
Add TPU filament

### ISSUE THREAD

**Issue by kyelisavenko** [suchmememanyskill/PrusaSlicer-Ender3-v3-SE-Config#1]
First and foremost, I much appreciate your profiles. You are the timesaver for a lot of people. Thanks.
I want to ask if there is a chance to see a TPU filament configuration in the nearest perspective. It would be great to have it in addition to the most popular PLA and PETG.
Thanks in advance.

**Comment by suchmememanyskill** [comment]
I can try to look into it, sure. I ordered a roll of TPU so i can try to make a profile around it. Do note i am unavailable for the next few weeks so it may take a while before i get around to this. 

Although i suspect a good starting point would be to start from a PLA profile and limit the volumetric flow rate to 2 or 3mm^3/s and decreasing the retraction speed to around 30mm/s

**Comment by kyelisavenko** [comment]
You don't need to rush at all. Will try some calibration details based on your recommendations. Thanks

**Comment by suchmememanyskill** [comment]
If you can find a reasonable setup, would you mind sending a pull request with the profile?

**Comment by suchmememanyskill** [comment]
Can someone else try my TPU profile? You can either copy the .ini manually or use the auto generated config bundle: https://github.com/suchmememanyskill/PrusaSlicer-Ender3-v3-SE-Config/actions/runs/6871042960
