### ISSUE TITLE
Suggestion "Bed temperature" for "other layers" 50

### ISSUE THREAD

**Issue by foobnix** [suchmememanyskill/PrusaSlicer-Ender3-v3-SE-Config#10]
I added one change "Bed temperature" for "other layers" 50-55 (not 60)
For some of my models, it is too hot in the bottom layers

**Comment by suchmememanyskill** [comment]
Are you using the included PC bed or another type of bed like PEI

**Comment by foobnix** [comment]
I am using default Printer bed

**Comment by suchmememanyskill** [comment]
So the PC bed. Yes, that will need slightly lower temperatures.

I personally use a PEI bed, which need higher temperatures than the default bed. This is what the profile is tuned for. I think arguably everyone should be running a PEI bed, the included PC one is inconsistent.

For how to solve this, i'm unsure.

**Comment by foobnix** [comment]
Close as invalid, decreasing the nozzle temperature helps me.
