### ISSUE TITLE
Suggestion Skirt Loops to 0

### ISSUE THREAD

**Issue by foobnix** [suchmememanyskill/PrusaSlicer-Ender3-v3-SE-Config#11]
All my models successfully print without skirt loops, why do we need it?

**Comment by suchmememanyskill** [comment]
This is a little awkward, i've just pushed to remove the purge line and run an extra skirt line to compensate.

In future releases it will be used as a purge line

**Comment by suchmememanyskill** [comment]
Closing due to the skirt being used as a purge line now
