### ISSUE TITLE
0,08mm profile.

### ISSUE THREAD

**Issue by sephiroth986** [suchmememanyskill/PrusaSlicer-Ender3-v3-SE-Config#22]
hi

i have downloaded your profile, but i have only 0,020mm profile. can you implement 0,08mm ?? i need it for printing good quality fantasy miniatures. thanks a lot!

**Comment by suchmememanyskill** [comment]
You should have a slow 0.1mm profile. You can modify that to be 0.08mm if you wish

I'm not planning to add a .08mm profile as i don't think it'll give much benefit over .1mm
