### ISSUE TITLE
blobs and zits when printing 

### ISSUE THREAD

**Issue by keysCodes** [suchmememanyskill/PrusaSlicer-Ender3-v3-SE-Config#32]
been using this profile perfectly fine for a while then this started happening
![problem 2](https://github.com/suchmememanyskill/PrusaSlicer-Ender3-v3-SE-Config/assets/145821431/32b7b1f5-fd32-4d99-bb41-dc6c8b3bcae1) theres also a lot of zits around a lot of different prints

**Comment by keysCodes** [comment]
also i got the nebula pad and when i got it the prints started out perfect but after a couple weeks it stopped coming out perfect so its prob not a pad issue (i use the klipper version on the cfg because nebula has klipper)

**Comment by suchmememanyskill** [comment]
By that same logic, why would this profile be the issue then, if it worked before?

It's possible your filament isn't dry, please do check that

**Comment by keysCodes** [comment]
yes i have i have dehydrated it many times and its not brittle so

**Comment by keysCodes** [comment]
also it works with other slicers just that they have other problems but the prusa profile before it had issues didnt

**Comment by suchmememanyskill** [comment]
What does 'before' and 'after' mean in this context? If the profile didn't change i'm unsure how this is my issue

**Comment by keysCodes** [comment]
before it stopped working and after

**Comment by suchmememanyskill** [comment]
> If the profile didn't change i'm unsure how this is my issue

Closing this issue, this seems to be an issue dictacted by outside factors, not the profile

**Comment by keysCodes** [comment]
do you atleast know of a possible fix?
