### ISSUE TITLE
Top layer issue

### ISSUE THREAD

**Issue by adiasbr** [suchmememanyskill/PrusaSlicer-Ender3-v3-SE-Config#33]
My top layer is with a poor quality using this profile.

**Comment by suchmememanyskill** [comment]
Define 'poor'?

Do other slicers give better results?

Did you try with different filaments?

**Comment by suchmememanyskill** [comment]
@adiasbr could you give the proposed change in https://github.com/suchmememanyskill/PrusaSlicer-Ender3-v3-SE-Config/discussions/39#discussioncomment-9252930 a go?

**Comment by suchmememanyskill** [comment]
Released
