### ISSUE TITLE
Parámetros Ender 3 v3 SE PRUSA

### ISSUE THREAD

**Issue by torete2024** [suchmememanyskill/PrusaSlicer-Ender3-v3-SE-Config#36]
Hola después de mucho tiempo ya puedo decir que tengo algo parecido a un buen trabajo.Boquilla 0.2mm.
![IMG_20240401_034840](https://github.com/suchmememanyskill/PrusaSlicer-Ender3-v3-SE-Config/assets/163774792/80fc682c-5880-4251-8c17-a6dfc406c7b4)

**Comment by torete2024** [comment]
Boquilla 0.4mm
![IMG_20240401_050249](https://github.com/suchmememanyskill/PrusaSlicer-Ender3-v3-SE-Config/assets/163774792/f95d6d01-e2e7-4696-a8a9-a3f7351bc2a1)

**Comment by suchmememanyskill** [comment]
I don't speak Spanish, why did you open an issus about this?

**Comment by torete2024** [comment]
Ha sido un error
