### ISSUE TITLE
Console Filled With Invalid (M204 command "M204 P500" & Invalid M204 command "M204 P2500")

### ISSUE THREAD

**Issue by Shubham-Sus** [suchmememanyskill/PrusaSlicer-Ender3-v3-SE-Config#38]
who can i fix this my console is filled with these invalid command while i am printing no issue with prints though is this anything related to your config?
11:51:44 
// Invalid M204 command "M204 P500"
11:51:44 
// Invalid M204 command "M204 P2500"

**Comment by suchmememanyskill** [comment]
Are you using Klipper or Marlin? And are you using the profile that matches that firmware?

**Comment by Shubham-Sus** [comment]
> Are you using Klipper or Marlin? And are you using the profile that matches that firmware?

Sorry, I didn't select the Klipper profile, so that was the issue. Thanks anyway.
